---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token
  namespace: infisical-secrets
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    instantUpdates: true
    resyncInterval: 15m
  authentication:
    kubernetesAuth:
      identityId: "431882cb-5d6c-4655-8db7-c3089d8d7dc8"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-auth
        namespace: infisical
      secretsScope:
        projectId: "d0ce9d00-ee31-4669-b3ca-0fcbb593f862"
        envSlug: prod
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: cloudflare-api-token
      secretNamespace: cert-manager
      template:
        includeAllSecrets: false
        data:
          api-token: "{{ .CLOUDFLARE_DNS_API_TOKEN.Value }}"
