apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: doc-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: ghcr.io/idanycb/findoc-rag-frontend:main-6-690092c3d0674d3015e6678bb8e8f12992249af7 # {"$imagepolicy": "doc-analyzer:frontend-policy"}
          name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
