---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: frontend
  namespace: doc-analyzer
spec:
  image: ghcr.io/idanycb/findoc-rag-frontend
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: frontend-policy
  namespace: doc-analyzer
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    alphabetical: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: frontend-update
  namespace: doc-analyzer
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "Update frontend image to {{ .NewImage }}"
  update:
    path: "./apps/doc-analyzer/frontend"
    strategy: Setters
