---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 12h
  chart:
    spec:
      chart: traefik
      version: "39.0.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
    providers:
      kubernetesGateway:
        enabled: true
    ports:
      web:
        port: 80
        expose: true
        protocol: TCP
      websecure:
        port: 443
        expose: true
        protocol: TCP
    additionalArguments:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-danycb-tech-tls

    deployment:
      replicas: 2

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
