apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: findoc-analyzer-secrets
  namespace: doc-analyzer
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    instantUpdates: true
    resyncInterval: 15m
  authentication:
    kubernetesAuth:
      identityId: "431882cb-5d6c-4655-8db7-c3089d8d7dc8"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-auth
        namespace: infisical
      secretsScope:
        projectId: "d0ce9d00-ee31-4669-b3ca-0fcbb593f862"
        envSlug: doc-analyzer
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: findoc-analyzer-secrets
      secretNamespace: doc-analyzer
      template:
        includeAllSecrets: false
        data:
          AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID.Value }}"
          AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY.Value }}"
          GROQ_API_KEY: "{{ .GROQ_API_KEY.Value }}"
          JWT_SECRET: "{{ .JWT_SECRET.Value }}"
          POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD.Value }}"
