---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: portfolio
  namespace: portfolio
spec:
  image: ghcr.io/idanycb/portfolio
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: portfolio-policy
  namespace: portfolio
spec:
  imageRepositoryRef:
    name: portfolio
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: portfolio-update
  namespace: portfolio
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "Update portfolio image"
  update:
    path: "./apps/portfolio"
    strategy: Setters
