apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: portfolio-secrets
  namespace: portfolio
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    instantUpdates: true
    resyncInterval: 15m
  authentication:
    kubernetesAuth:
      identityId: "431882cb-5d6c-4655-8db7-c3089d8d7dc8"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-auth
        namespace: infisical
      secretsScope:
        projectId: "d0ce9d00-ee31-4669-b3ca-0fcbb593f862"
        envSlug: prod
        secretsPath: /portfolio
  managedKubeSecretReferences:
    - secretName: portfolio-secrets
      secretNamespace: portfolio
      template:
        includeAllSecrets: false
        data:
          CONTACT_FROM_EMAIL: "{{ .CONTACT_FROM_EMAIL.Value }}"
          CONTACT_TO_EMAIL: "{{ .CONTACT_TO_EMAIL.Value }}"
          RESEND_API_KEY: "{{ .RESEND_API_KEY.Value }}"
          TURNSTILE_SECRET_KEY: "{{ .TURNSTILE_SECRET_KEY.Value }}"
